### ISSUE TITLE
Some English strings left empty

### ISSUE THREAD

**Issue by mudrd8mz** [ponlawat-w/moodle-calendartype_thaibuddhist#1]
The file `lang/en/calendartype_thaibuddhist.php` now has some strings left empty
```
$string['months'] = '';
$string['shortmonths'] = '';
$string['days'] = '';
$string['shortdays'] = '';
```
I don't suppose that's intentional?

**Comment by ponlawat-w** [comment]
Thank you for your comment.

Those English strings are intentionally left blank.
The reason is that Moodle and `strftime` function does not display date properly in Thai language, it is still English (Mon ~ Sun, Jan ~ Dec), so the strings are for replacing them.
If those strings are blank, it will use default `strftime` function without replacing any text.
